"""
  This is a simple python script to test the autogenerated module

"""
import os
import sys
import time

path = `os.environ.get("AL_DIR")`
home = `os.environ.get("HOME")`

# import NaoQi lib
if path == "None":
  print "the environnement variable AL_DIR is not set, aborting..."
  sys.exit(1)
else:
  alPath = path + "/lib"
  alPath = alPath.replace("~", home)
  alPath = alPath.replace("'", "")
  sys.path.append(alPath)
  import naoqi
  from naoqi import ALBroker
  from naoqi import ALModule
  from naoqi import ALProxy
  from naoqi import ALBehavior
  from vision_definitions import*

for arg in sys.argv:
	print arg
	IP = arg

PORT = 9559


imgPathOriginal="/home/nao/fotos/original"
imgPathProcessed="/home/nao/fotos/processed"

#________________________________
# Generic Proxy creation 
#________________________________

try:
  vision1_Proxy = ALProxy("vision1",IP,PORT)
except Exception,e:
  print "Error when creating STMOBJECT_NAME  proxy:"
  print str(e)
  exit(1)

#print "Init"
#vision1_Proxy.init()

#print "Registering to VIM"
#vision1_Proxy.registerToVIM(kQQVGA, kRGBColorSpace)

#print "takePicture"
vision1_Proxy.takePicture(imgPathOriginal)


print "Stiffness On"
vision1_Proxy.stiffnessOn()

print "Processing Image"
vision1_Proxy.processBall(imgPathProcessed)

#vision1_Proxy.saveData("/home/nao/fotos/dump.txt")

print "Stiffness Off"
vision1_Proxy.stiffnessOff()

#print "write"
#vision1_Proxy.write()


exit(0)
